import { COLORS, SIZES } from '~tokens/index'

export const CSSVariablesHostToRootCases = [
  { host: '--y-core-simple-checkbox-size-small-padding', root: '--y-core-size-spacing-0-5-x' },
  { host: '--y-core-simple-checkbox-size-medium-padding', root: '--y-core-size-spacing-0-5-x' },
  { host: '--y-core-simple-checkbox-default-background-color', root: '--y-core-color-surface-primary' },
  { host: '--y-core-simple-checkbox-default-border-color', root: '--y-core-color-stroke-primary' },
  { host: '--y-core-simple-checkbox-default-icon-color', root: '--y-core-color-icon-on-accent' },
  { host: '--y-core-simple-checkbox-default-hover-background-color', root: '--y-core-color-surface-primary-high' },
  { host: '--y-core-simple-checkbox-default-hover-border-color', root: '--y-core-color-stroke-primary-high' },
  { host: '--y-core-simple-checkbox-checked-background-color', root: '--y-core-color-surface-accent' },
  { host: '--y-core-simple-checkbox-checked-border-color', root: '--y-core-color-surface-accent' },
  { host: '--y-core-simple-checkbox-checked-hover-background-color', root: '--y-core-color-surface-accent-high' },
  { host: '--y-core-simple-checkbox-checked-hover-border-color', root: '--y-core-color-surface-accent-high' },
  { host: '--y-core-simple-checkbox-checked-hover-icon-color', root: '--y-core-color-icon-on-accent' },
  { host: '--y-core-simple-checkbox-indeterminate-icon-color', root: '--y-core-color-icon-accent' },
  { host: '--y-core-simple-checkbox-indeterminate-hover-background-color', root: '--y-core-color-surface-primary-high' },
  { host: '--y-core-simple-checkbox-indeterminate-hover-border-color', root: '--y-core-color-stroke-primary-high' },
  { host: '--y-core-simple-checkbox-indeterminate-hover-icon-color', root: '--y-core-color-surface-accent-high' },
  { host: '--y-core-simple-checkbox-error-background-color', root: '--y-core-color-surface-negative' },
  { host: '--y-core-simple-checkbox-error-border-color', root: '--y-core-color-surface-negative' },
  { host: '--y-core-simple-checkbox-error-icon-color', root: '--y-core-color-other-contrast' },
  { host: '--y-core-simple-checkbox-disabled-color', root: '--y-core-color-stroke-primary-low' },
  { host: '--y-core-simple-checkbox-disabled-checked-color', root: '--y-core-color-surface-accent-low' },
  { host: '--y-core-simple-checkbox-disabled-icon-color', root: '--y-core-color-icon-tertiary' },
]

export const CSSVariablesHostToValueCases = [
  { host: '--y-core-simple-checkbox-size-small-padding', value: SIZES.spacing_0_5_x.cssValue },
  { host: '--y-core-simple-checkbox-size-medium-padding', value: SIZES.spacing_0_5_x.cssValue },
  { host: '--y-core-simple-checkbox-default-background-color', value: COLORS.surface_primary.cssValue },
  { host: '--y-core-simple-checkbox-default-border-color', value: COLORS.stroke_primary.cssValue },
  { host: '--y-core-simple-checkbox-default-icon-color', value: COLORS.icon_on_accent.cssValue },
  { host: '--y-core-simple-checkbox-default-hover-background-color', value: COLORS.surface_primary_high.cssValue },
  { host: '--y-core-simple-checkbox-default-hover-border-color', value: COLORS.stroke_primary_high.cssValue },
  { host: '--y-core-simple-checkbox-checked-background-color', value: COLORS.surface_accent.cssValue },
  { host: '--y-core-simple-checkbox-checked-border-color', value: COLORS.surface_accent.cssValue },
  { host: '--y-core-simple-checkbox-checked-hover-background-color', value: COLORS.surface_accent_high.cssValue },
  { host: '--y-core-simple-checkbox-checked-hover-border-color', value: COLORS.surface_accent_high.cssValue },
  { host: '--y-core-simple-checkbox-checked-hover-icon-color', value: COLORS.icon_on_accent.cssValue },
  { host: '--y-core-simple-checkbox-indeterminate-icon-color', value: COLORS.icon_accent.cssValue },
  { host: '--y-core-simple-checkbox-indeterminate-hover-background-color', value: COLORS.surface_primary_high.cssValue },
  { host: '--y-core-simple-checkbox-indeterminate-hover-border-color', value: COLORS.stroke_primary_high.cssValue },
  { host: '--y-core-simple-checkbox-indeterminate-hover-icon-color', value: COLORS.surface_accent_high.cssValue },
  { host: '--y-core-simple-checkbox-error-background-color', value: COLORS.surface_negative.cssValue },
  { host: '--y-core-simple-checkbox-error-border-color', value: COLORS.surface_negative.cssValue },
  { host: '--y-core-simple-checkbox-error-icon-color', value: COLORS.other_contrast.cssValue },
  { host: '--y-core-simple-checkbox-disabled-color', value: COLORS.stroke_primary_low.cssValue },
  { host: '--y-core-simple-checkbox-disabled-checked-color', value: COLORS.surface_accent_low.cssValue },
  { host: '--y-core-simple-checkbox-disabled-icon-color', value: COLORS.icon_tertiary.cssValue },
]
