import { SIZES, COLORS, TYPOGRAPHY } from '~root/tokens'

export const CSSVariablesHostToRootCases = [
  { host: '--y-core-field-wrapper-border-color', root: '--y-core-color-stroke-primary' },
  { host: '--y-core-field-wrapper-default-hover-border-color', root: '--y-core-color-stroke-primary-high' },
  { host: '--y-core-field-wrapper-default-background-color', root: '--y-core-color-surface-primary' },
  { host: '--y-core-field-wrapper-default-color', root: '--y-core-color-text-primary' },
  { host: '--y-core-field-wrapper-disabled-border-color', root: '--y-core-color-stroke-primary' },
  { host: '--y-core-field-wrapper-disabled-background-color', root: '--y-core-color-surface-primary-high' },
  { host: '--y-core-field-wrapper-disabled-color', root: '--y-core-color-text-tertiary' },
  { host: '--y-core-field-wrapper-readonly-background-color', root: '--y-core-color-surface-primary-high' },
  { host: '--y-core-field-wrapper-focused-border-color', root: '--y-core-color-stroke-accent' },
  { host: '--y-core-field-wrapper-error-border-color', root: '--y-core-color-stroke-negative' },
  { host: '--y-core-field-wrapper-size-small-font-size', root: '--y-core-typography-paragraph-p-2-regular-font-size' },
  { host: '--y-core-field-wrapper-size-small-line-height', root: '--y-core-typography-paragraph-p-2-regular-line-height' },
  { host: '--y-core-field-wrapper-size-small-border-radius', root: '--y-core-size-radius-2-x' },
  { host: '--y-core-field-wrapper-size-medium-font-size', root: '--y-core-typography-paragraph-p-1-regular-font-size' },
  { host: '--y-core-field-wrapper-size-medium-line-height', root: '--y-core-typography-paragraph-p-1-regular-line-height' },
  { host: '--y-core-field-wrapper-size-medium-border-radius', root: '--y-core-size-radius-2-5-x' },
  { host: '--y-core-field-wrapper-size-large-font-size', root: '--y-core-typography-paragraph-p-1-regular-font-size' },
  { host: '--y-core-field-wrapper-size-large-line-height', root: '--y-core-typography-paragraph-p-1-regular-line-height' },
  { host: '--y-core-field-wrapper-size-large-border-radius', root: '--y-core-size-radius-3-x' },
]

export const CSSVariablesHostToValueCases = [
  { host: '--y-core-field-wrapper-border-color', value: COLORS.stroke_primary.cssValue },
  { host: '--y-core-field-wrapper-default-hover-border-color', value: COLORS.stroke_primary_high.cssValue },
  { host: '--y-core-field-wrapper-default-background-color', value: COLORS.surface_primary.cssValue },
  { host: '--y-core-field-wrapper-default-color', value: COLORS.text_primary.cssValue },
  { host: '--y-core-field-wrapper-disabled-border-color', value: COLORS.stroke_primary.cssValue },
  { host: '--y-core-field-wrapper-disabled-background-color', value: COLORS.surface_primary_high.cssValue },
  { host: '--y-core-field-wrapper-disabled-color', value: COLORS.text_tertiary.cssValue },
  { host: '--y-core-field-wrapper-readonly-background-color', value: COLORS.surface_primary_high.cssValue },
  { host: '--y-core-field-wrapper-focused-border-color', value: COLORS.stroke_accent.cssValue },
  { host: '--y-core-field-wrapper-error-border-color', value: COLORS.stroke_negative.cssValue },
  { host: '--y-core-field-wrapper-size-small-font-size', value: TYPOGRAPHY.paragraph_p_2_regular_font_size.cssValue },
  { host: '--y-core-field-wrapper-size-small-line-height', value: TYPOGRAPHY.paragraph_p_2_regular_line_height.cssValue },
  { host: '--y-core-field-wrapper-size-small-border-radius', value: SIZES.radius_2_x.cssValue },
  { host: '--y-core-field-wrapper-size-medium-font-size', value: TYPOGRAPHY.paragraph_p_1_regular_font_size.cssValue },
  { host: '--y-core-field-wrapper-size-medium-line-height', value: TYPOGRAPHY.paragraph_p_1_regular_line_height.cssValue },
  { host: '--y-core-field-wrapper-size-medium-border-radius', value: SIZES.radius_2_5_x.cssValue },
  { host: '--y-core-field-wrapper-size-large-font-size', value: TYPOGRAPHY.paragraph_p_1_regular_font_size.cssValue },
  { host: '--y-core-field-wrapper-size-large-line-height', value: TYPOGRAPHY.paragraph_p_1_regular_line_height.cssValue },
  { host: '--y-core-field-wrapper-size-large-border-radius', value: SIZES.radius_3_x.cssValue },
]
