import { EXTENDED_COLORS, SIZES, AVATAR } from '~root/tokens'

export const CSSVariablesHostToRootCases = [
  { host: '--y-avatar-gap', root: '--y-core-size-spacing-2-5-x' },
  { host: '--y-avatar-size-extra-small', root: '--y-core-component-avatar-size-100' },
  { host: '--y-avatar-size-small', root: '--y-core-component-avatar-size-300' },
  { host: '--y-avatar-size-medium', root: '--y-core-component-avatar-size-500' },
  { host: '--y-avatar-size-large', root: '--y-core-component-avatar-size-800' },
  { host: '--y-avatar-font-size-extra-small', root: '--y-core-component-avatar-initial-font-size-size-100' },
  { host: '--y-avatar-line-height-extra-small', root: '--y-core-component-avatar-initial-line-height-size-100' },
  { host: '--y-avatar-font-size-small', root: '--y-core-component-avatar-initial-font-size-size-300' },
  { host: '--y-avatar-line-height-small', root: '--y-core-component-avatar-initial-line-height-size-300' },
  { host: '--y-avatar-font-size-medium', root: '--y-core-component-avatar-initial-font-size-size-500' },
  { host: '--y-avatar-line-height-medium', root: '--y-core-component-avatar-initial-line-height-size-500' },
  { host: '--y-avatar-font-size-large', root: '--y-core-component-avatar-initial-font-size-size-800' },
  { host: '--y-avatar-line-height-large', root: '--y-core-component-avatar-initial-line-height-size-800' },
  { host: '--y-avatar-radius-extra-small', root: '--y-core-size-radius-x' },
  { host: '--y-avatar-radius-small', root: '--y-core-size-radius-1-5-x' },
  { host: '--y-avatar-radius-medium', root: '--y-core-size-radius-2-x' },
  { host: '--y-avatar-radius-large', root: '--y-core-size-radius-3-x' },
  { host: '--y-avatar-bg', root: '--y-core-color-calm-surface-purple-low' },
  { host: '--y-avatar-text-color', root: '--y-core-color-calm-icon-purple' },
]

export const CSSVariablesHostToValueCases = [
  { host: '--y-avatar-gap', value: SIZES.spacing_2_5_x.cssValue },
  { host: '--y-avatar-size-extra-small', value: AVATAR.avatar_size_100.cssValue },
  { host: '--y-avatar-size-small', value: AVATAR.avatar_size_300.cssValue },
  { host: '--y-avatar-size-medium', value: AVATAR.avatar_size_500.cssValue },
  { host: '--y-avatar-size-large', value: AVATAR.avatar_size_800.cssValue },
  { host: '--y-avatar-font-size-extra-small', value: AVATAR.avatar_initial_font_size_size_100.cssValue },
  { host: '--y-avatar-font-size-small', value: AVATAR.avatar_initial_font_size_size_300.cssValue },
  { host: '--y-avatar-font-size-medium', value: AVATAR.avatar_initial_font_size_size_500.cssValue },
  { host: '--y-avatar-font-size-large', value: AVATAR.avatar_initial_font_size_size_800.cssValue },
  { host: '--y-avatar-line-height-extra-small', value: AVATAR.avatar_initial_line_height_size_100.cssValue },
  { host: '--y-avatar-line-height-small', value: AVATAR.avatar_initial_line_height_size_300.cssValue },
  { host: '--y-avatar-line-height-medium', value: AVATAR.avatar_initial_line_height_size_500.cssValue },
  { host: '--y-avatar-line-height-large', value: AVATAR.avatar_initial_line_height_size_800.cssValue },
  { host: '--y-avatar-radius-extra-small', value: SIZES.radius_x.cssValue },
  { host: '--y-avatar-radius-small', value: SIZES.radius_1_5_x.cssValue },
  { host: '--y-avatar-radius-medium', value: SIZES.radius_2_x.cssValue },
  { host: '--y-avatar-radius-large', value: SIZES.radius_3_x.cssValue },
  { host: '--y-avatar-bg', value: EXTENDED_COLORS.calm_surface_purple_low.cssValue },
  { host: '--y-avatar-text-color', value: EXTENDED_COLORS.calm_icon_purple.cssValue },
]
