export const YC_TEXT_PRIMARY = '#262626'
export const YC_TEXT_SECONDARY = 'rgba(38, 38, 38, 0.6)'
export const YC_TEXT_TERTIARY = 'rgba(38, 38, 38, 0.26)'
export const YC_TEXT_POSITIVE = '#29c235'
export const YC_TEXT_NEGATIVE = '#f72c32'
export const YC_TEXT_NEGATIVE_LOW = 'rgba(247, 44, 50, 0.25)'
export const YC_TEXT_WARNING = '#d97f02'
export const YC_TEXT_WARNING_LOW = 'rgba(217, 127, 2, 0.25)'
export const YC_TEXT_ACCENT = '#ffcb00'
export const YC_ICON_PRIMARY = '#262626'
export const YC_ICON_SECONDARY = 'rgba(38, 38, 38, 0.6)'
export const YC_ICON_TERTIARY = 'rgba(38, 38, 38, 0.26)'
export const YC_ICON_POSITIVE = '#29c235'
export const YC_ICON_NEGATIVE = '#f72c32'
export const YC_ICON_NEGATIVE_LOW = 'rgba(247, 44, 50, 0.25)'
export const YC_ICON_WARNING = '#d97f02'
export const YC_ICON_ACCENT = '#ffcb00'
export const YC_ICON_ACCENT_LOW = 'rgba(255, 203, 0, 0.3)'
export const YC_ICON_ACCENT_HIGH = '#ffa800'
export const YC_STROKE_PRIMARY = 'rgba(38, 38, 38, 0.15)'
export const YC_STROKE_PRIMARY_LOW = 'rgba(38, 38, 38, 0.05)'
export const YC_STROKE_PRIMARY_HIGH = 'rgba(38, 38, 38, 0.25)'
export const YC_STROKE_SECONDARY = 'rgba(38, 38, 38, 0.03)'
export const YC_STROKE_SECONDARY_LOW = '#ffffff'
export const YC_STROKE_POSITIVE = '#29c235'
export const YC_STROKE_NEGATIVE = '#f72c32'
export const YC_STROKE_WARNING = '#d97f02'
export const YC_STROKE_ACCENT = '#ffcb00'
export const YC_SURFACE_PRIMARY = '#ffffff'
export const YC_SURFACE_PRIMARY_HIGH = 'rgba(38, 38, 38, 0.02)'
export const YC_SURFACE_SECONDARY = 'rgba(38, 38, 38, 0.03)'
export const YC_SURFACE_SECONDARY_LOW = 'rgba(38, 38, 38, 0.02)'
export const YC_SURFACE_SECONDARY_HIGH = 'rgba(38, 38, 38, 0.05)'
export const YC_SURFACE_SECONDARY_FILL = '#f8f8f9'
export const YC_SURFACE_TERTIARY = 'rgba(38, 38, 38, 0.07)'
export const YC_SURFACE_TERTIARY_LOW = 'rgba(38, 38, 38, 0.05)'
export const YC_SURFACE_TERTIARY_HIGH = 'rgba(38, 38, 38, 0.2)'
export const YC_SURFACE_POSITIVE = '#29c235'
export const YC_SURFACE_POSITIVE_LOW = 'rgba(41, 194, 53, 0.22)'
export const YC_SURFACE_NEGATIVE = '#f72c32'
export const YC_SURFACE_NEGATIVE_LOW = 'rgba(247, 44, 50, 0.15)'
export const YC_SURFACE_NEGATIVE_HIGH = '#d1050b'
export const YC_SURFACE_WARNING = 'rgba(255, 203, 0, 0.1)'
export const YC_SURFACE_ACCENT = '#ffcb00'
export const YC_OTHER_CONTRAST = '#ffffff'
export const YC_OTHER_INVERT = '#444951'
export const YC_OTHER_LINK = '#003acc'
export const YC_OTHER_OVERLAY_60 = 'rgba(0, 0, 0, 0.6)'
export const YC_OTHER_BASE = '#f3f3f3'
export const YC_TEXT_ON_ACCENT = '#262626'
export const YC_ICON_ON_ACCENT = '#262626'
export const YC_SURFACE_ACCENT_LOW = 'rgba(255, 203, 0, 0.3)'
export const YC_OTHER_BRAND_WHATSAPP = '#0077ff'
export const YC_OTHER_BRAND_WHATSAPP_HIGH = '#0273f8'
export const YC_SURFACE_ACCENT_HIGH = '#ffa800'
export const YC_STATIC_WHITE = '#ffffff'
export const YC_SHADOW_ACCENT = '#ffcb00'
export const YC_STATIC_BLACK = '#000000'

export const YC_CALM_TEXT_GREEN = '#219464'
export const YC_CALM_ICON_GREEN = '#219464'
export const YC_CALM_STROKE_GREEN = '#219464'
export const YC_CALM_SURFACE_GREEN = '#219464'
export const YC_CALM_SURFACE_GREEN_LOW = 'rgba(33, 148, 100, 0.1)'
export const YC_CALM_SURFACE_BLUE = '#2f53e3'
export const YC_CALM_SURFACE_BLUE_LOW = 'rgba(47, 83, 227, 0.1)'
export const YC_CALM_SURFACE_ORANGE = '#df7800'
export const YC_CALM_SURFACE_ORANGE_LOW = 'rgba(223, 120, 0, 0.1)'
export const YC_CALM_SURFACE_YELLOW = '#f8bc3b'
export const YC_CALM_SURFACE_YELLOW_LOW = 'rgba(248, 188, 59, 0.2)'
export const YC_CALM_SURFACE_RED = '#e34f2f'
export const YC_CALM_SURFACE_RED_LOW = 'rgba(227, 79, 47, 0.1)'
export const YC_CALM_SURFACE_PURPLE = '#6644e0'
export const YC_CALM_SURFACE_PURPLE_LOW = 'rgba(102, 68, 224, 0.1)'
export const YC_CALM_SURFACE_TEAL = '#5bb7af'
export const YC_CALM_SURFACE_TEAL_LOW = 'rgba(91, 183, 175, 0.1)'
export const YC_CALM_SURFACE_PEARL = '#ffb27a'
export const YC_CALM_SURFACE_PEARL_LOW = 'rgba(255, 178, 122, 0.1)'
export const YC_CALM_SURFACE_PLUM = '#b2596e'
export const YC_CALM_SURFACE_PLUM_LOW = 'rgba(178, 89, 110, 0.1)'
export const YC_CALM_SURFACE_CERULEAN = '#0d7ea0'
export const YC_CALM_SURFACE_CERULEAN_LOW = 'rgba(13, 126, 160, 0.1)'
export const YC_CALM_SURFACE_AQUA = '#72bef4'
export const YC_CALM_SURFACE_AQUA_LOW = 'rgba(114, 190, 244, 0.1)'
export const YC_CALM_STROKE_GREEN_LOW = 'rgba(33, 148, 100, 0.1)'
export const YC_CALM_STROKE_BLUE = '#2f53e3'
export const YC_CALM_STROKE_BLUE_LOW = 'rgba(47, 83, 227, 0.15)'
export const YC_CALM_STROKE_ORANGE = '#df7800'
export const YC_CALM_STROKE_ORANGE_LOW = 'rgba(223, 120, 0, 0.1)'
export const YC_CALM_STROKE_YELLOW = '#f8bc3b'
export const YC_CALM_STROKE_YELLOW_LOW = 'rgba(248, 188, 59, 0.2)'
export const YC_CALM_STROKE_RED = '#e34f2f'
export const YC_CALM_STROKE_RED_LOW = 'rgba(227, 79, 47, 0.1)'
export const YC_CALM_STROKE_PURPLE = '#6644e0'
export const YC_CALM_STROKE_PURPLE_LOW = 'rgba(79, 68, 224, 0.1)'
export const YC_CALM_STROKE_TEAL = '#5bb7af'
export const YC_CALM_STROKE_TEAL_LOW = 'rgba(91, 183, 175, 0.1)'
export const YC_CALM_STROKE_PEARL = '#ffb27a'
export const YC_CALM_STROKE_PEARL_LOW = 'rgba(255, 178, 122, 0.1)'
export const YC_CALM_STROKE_PLUM = '#b2596e'
export const YC_CALM_STROKE_PLUM_LOW = 'rgba(178, 89, 110, 0.1)'
export const YC_CALM_STROKE_CERULEAN = '#0d7ea0'
export const YC_CALM_STROKE_CERULEAN_LOW = 'rgba(13, 126, 160, 0.1)'
export const YC_CALM_STROKE_AQUA = '#72bef4'
export const YC_CALM_STROKE_AQUA_LOW = 'rgba(114, 190, 244, 0.1)'
export const YC_CALM_ICON_GREEN_LOW = 'rgba(33, 148, 100, 0.2)'
export const YC_CALM_ICON_BLUE = '#2f53e3'
export const YC_CALM_ICON_BLUE_LOW = 'rgba(47, 83, 227, 0.2)'
export const YC_CALM_ICON_ORANGE = '#df7800'
export const YC_CALM_ICON_ORANGE_LOW = 'rgba(223, 120, 0, 0.15)'
export const YC_CALM_ICON_YELLOW = '#f8bc3b'
export const YC_CALM_ICON_YELLOW_LOW = 'rgba(248, 188, 59, 0.2)'
export const YC_CALM_ICON_RED = '#e34f2f'
export const YC_CALM_ICON_RED_LOW = 'rgba(227, 79, 47, 0.2)'
export const YC_CALM_ICON_PURPLE = '#6644e0'
export const YC_CALM_ICON_PURPLE_LOW = 'rgba(79, 68, 224, 0.2)'
export const YC_CALM_ICON_TEAL = '#5bb7af'
export const YC_CALM_ICON_TEAL_LOW = 'rgba(91, 183, 175, 0.2)'
export const YC_CALM_ICON_PEARL = '#ffb27a'
export const YC_CALM_ICON_PEARL_LOW = 'rgba(255, 178, 122, 0.2)'
export const YC_CALM_ICON_PLUM = '#b2596e'
export const YC_CALM_ICON_PLUM_LOW = 'rgba(178, 89, 110, 0.2)'
export const YC_CALM_ICON_CERULEAN = '#0d7ea0'
export const YC_CALM_ICON_CERULEAN_LOW = 'rgba(13, 126, 160, 0.2)'
export const YC_CALM_ICON_AQUA = '#72bef4'
export const YC_CALM_ICON_AQUA_LOW = 'rgba(114, 190, 244, 0.2)'
export const YC_CALM_TEXT_GREEN_LOW = 'rgba(33, 148, 100, 0.2)'
export const YC_CALM_TEXT_BLUE = '#2f53e3'
export const YC_CALM_TEXT_BLUE_LOW = 'rgba(47, 83, 227, 0.2)'
export const YC_CALM_TEXT_ORANGE = '#cc7a00'
export const YC_CALM_TEXT_ORANGE_LOW = 'rgba(204, 122, 0, 0.15)'
export const YC_CALM_TEXT_YELLOW = '#f8bc3b'
export const YC_CALM_TEXT_YELLOW_LOW = 'rgba(248, 188, 59, 0.2)'
export const YC_CALM_TEXT_RED = '#e34f2f'
export const YC_CALM_TEXT_RED_LOW = 'rgba(227, 79, 47, 0.2)'
export const YC_CALM_TEXT_PURPLE = '#6644e0'
export const YC_CALM_TEXT_PURPLE_LOW = 'rgba(79, 68, 224, 0.2)'
export const YC_CALM_TEXT_TEAL = '#5bb7af'
export const YC_CALM_TEXT_TEAL_LOW = 'rgba(91, 183, 175, 0.2)'
export const YC_CALM_TEXT_PEARL = '#ffb27a'
export const YC_CALM_TEXT_PEARL_LOW = 'rgba(255, 178, 122, 0.2)'
export const YC_CALM_TEXT_PLUM = '#b2596e'
export const YC_CALM_TEXT_PLUM_LOW = 'rgba(178, 89, 110, 0.2)'
export const YC_CALM_TEXT_CERULEAN = '#0d7ea0'
export const YC_CALM_TEXT_CERULEAN_LOW = 'rgba(13, 126, 160, 0.2)'
export const YC_CALM_TEXT_AQUA = '#72bef4'
export const YC_CALM_TEXT_AQUA_LOW = 'rgba(114, 190, 244, 0.2)'
export const YC_SPORT_TEXT_GREEN = '#00d17a'
export const YC_SPORT_ICON_GREEN = '#00d17a'
export const YC_SPORT_STROKE_GREEN = '#00d17a'
export const YC_SPORT_STROKE_GREEN_LOW = 'rgba(0, 181, 105, 0.1)'
export const YC_SPORT_STROKE_BLUE = '#1342ff'
export const YC_SPORT_STROKE_BLUE_LOW = 'rgba(19, 66, 255, 0.1)'
export const YC_SPORT_STROKE_ORANGE = '#ff7308'
export const YC_SPORT_STROKE_ORANGE_LOW = 'rgba(255, 140, 5, 0.1)'
export const YC_SPORT_STROKE_YELLOW = '#ffe734'
export const YC_SPORT_STROKE_YELLOW_LOW = 'rgba(255, 231, 52, 0.2)'
export const YC_SPORT_STROKE_RED = '#ff3d13'
export const YC_SPORT_STROKE_RED_LOW = 'rgba(255, 61, 19, 0.1)'
export const YC_SPORT_STROKE_PURPLE = '#9a36ff'
export const YC_SPORT_STROKE_PURPLE_LOW = 'rgba(75, 25, 255, 0.1)'
export const YC_SPORT_STROKE_TEAL = '#21decd'
export const YC_SPORT_STROKE_TEAL_LOW = 'rgba(66, 208, 195, 0.1)'
export const YC_SPORT_STROKE_PEARL = '#ff6c5c'
export const YC_SPORT_STROKE_PEARL_LOW = 'rgba(255, 130, 92, 0.1)'
export const YC_SPORT_STROKE_PLUM = '#d7345a'
export const YC_SPORT_STROKE_PLUM_LOW = 'rgba(215, 52, 90, 0.1)'
export const YC_SPORT_STROKE_CERULEAN = '#009dcc'
export const YC_SPORT_STROKE_CERULEAN_LOW = 'rgba(0, 157, 204, 0.1)'
export const YC_SPORT_STROKE_AQUA = '#1fa2ff'
export const YC_SPORT_STROKE_AQUA_LOW = 'rgba(31, 162, 255, 0.1)'
export const YC_SPORT_ICON_GREEN_LOW = 'rgba(0, 181, 105, 0.2)'
export const YC_SPORT_ICON_BLUE = '#1342ff'
export const YC_SPORT_ICON_BLUE_LOW = 'rgba(19, 66, 255, 0.2)'
export const YC_SPORT_ICON_ORANGE = '#ff7308'
export const YC_SPORT_ICON_ORANGE_LOW = 'rgba(255, 140, 5, 0.15)'
export const YC_SPORT_ICON_YELLOW = '#ffe734'
export const YC_SPORT_ICON_YELLOW_LOW = 'rgba(255, 231, 52, 0.2)'
export const YC_SPORT_ICON_RED = '#ff3d13'
export const YC_SPORT_ICON_RED_LOW = 'rgba(255, 61, 19, 0.2)'
export const YC_SPORT_ICON_PURPLE = '#9a36ff'
export const YC_SPORT_ICON_PURPLE_LOW = 'rgba(75, 25, 255, 0.2)'
export const YC_SPORT_ICON_TEAL = '#21decd'
export const YC_SPORT_ICON_TEAL_LOW = 'rgba(66, 208, 195, 0.2)'
export const YC_SPORT_ICON_PEARL = '#ff6c5c'
export const YC_SPORT_ICON_PEARL_LOW = 'rgba(255, 130, 92, 0.2)'
export const YC_SPORT_ICON_PLUM = '#d7345a'
export const YC_SPORT_ICON_PLUM_LOW = 'rgba(215, 52, 90, 0.2)'
export const YC_SPORT_ICON_CERULEAN = '#009dcc'
export const YC_SPORT_ICON_CERULEAN_LOW = 'rgba(0, 157, 204, 0.2)'
export const YC_SPORT_ICON_AQUA = '#1fa2ff'
export const YC_SPORT_ICON_AQUA_LOW = 'rgba(31, 162, 255, 0.2)'
export const YC_SPORT_SURFACE_GREEN = '#00d17a'
export const YC_SPORT_SURFACE_GREEN_LOW = 'rgba(0, 181, 105, 0.1)'
export const YC_SPORT_SURFACE_BLUE = '#1342ff'
export const YC_SPORT_SURFACE_BLUE_LOW = 'rgba(19, 66, 255, 0.1)'
export const YC_SPORT_SURFACE_ORANGE = '#ff7308'
export const YC_SPORT_SURFACE_ORANGE_LOW = 'rgba(255, 140, 5, 0.1)'
export const YC_SPORT_SURFACE_YELLOW = '#ffe734'
export const YC_SPORT_SURFACE_YELLOW_LOW = 'rgba(255, 231, 52, 0.2)'
export const YC_SPORT_SURFACE_RED = '#ff3d13'
export const YC_SPORT_SURFACE_RED_LOW = 'rgba(255, 61, 19, 0.1)'
export const YC_SPORT_SURFACE_PURPLE = '#9a36ff'
export const YC_SPORT_SURFACE_PURPLE_LOW = 'rgba(154, 54, 255, 0.1)'
export const YC_SPORT_SURFACE_TEAL = '#21decd'
export const YC_SPORT_SURFACE_TEAL_LOW = 'rgba(33, 222, 205, 0.1)'
export const YC_SPORT_SURFACE_PEARL = '#ff6c5c'
export const YC_SPORT_SURFACE_PEARL_LOW = 'rgba(255, 108, 92, 0.1)'
export const YC_SPORT_SURFACE_PLUM = '#d7345a'
export const YC_SPORT_SURFACE_PLUM_LOW = 'rgba(215, 52, 90, 0.1)'
export const YC_SPORT_SURFACE_CERULEAN = '#009dcc'
export const YC_SPORT_SURFACE_CERULEAN_LOW = 'rgba(0, 157, 204, 0.1)'
export const YC_SPORT_SURFACE_AQUA = '#1fa2ff'
export const YC_SPORT_SURFACE_AQUA_LOW = 'rgba(31, 162, 255, 0.1)'
export const YC_SPORT_TEXT_GREEN_LOW = 'rgba(0, 209, 122, 0.2)'
export const YC_SPORT_TEXT_BLUE = '#1342ff'
export const YC_SPORT_TEXT_BLUE_LOW = 'rgba(19, 66, 255, 0.2)'
export const YC_SPORT_TEXT_ORANGE = '#ff7308'
export const YC_SPORT_TEXT_ORANGE_LOW = 'rgba(255, 115, 8, 0.15)'
export const YC_SPORT_TEXT_YELLOW = '#ffe734'
export const YC_SPORT_TEXT_YELLOW_LOW = 'rgba(255, 231, 52, 0.2)'
export const YC_SPORT_TEXT_RED = '#ff3d13'
export const YC_SPORT_TEXT_RED_LOW = 'rgba(255, 61, 19, 0.2)'
export const YC_SPORT_TEXT_PURPLE = '#9a36ff'
export const YC_SPORT_TEXT_PURPLE_LOW = 'rgba(75, 25, 255, 0.2)'
export const YC_SPORT_TEXT_TEAL = '#21decd'
export const YC_SPORT_TEXT_TEAL_LOW = 'rgba(66, 208, 195, 0.2)'
export const YC_SPORT_TEXT_PEARL = '#ff6c5c'
export const YC_SPORT_TEXT_PEARL_LOW = 'rgba(255, 130, 92, 0.2)'
export const YC_SPORT_TEXT_PLUM = '#d7345a'
export const YC_SPORT_TEXT_PLUM_LOW = 'rgba(215, 52, 90, 0.2)'
export const YC_SPORT_TEXT_CERULEAN = '#009dcc'
export const YC_SPORT_TEXT_CERULEAN_LOW = 'rgba(0, 157, 204, 0.2)'
export const YC_SPORT_TEXT_AQUA = '#1fa2ff'
export const YC_SPORT_TEXT_AQUA_LOW = 'rgba(31, 162, 255, 0.2)'

export const YC_SPACING_0_5_X = 2
export const YC_SPACING_X = 4
export const YC_SPACING_1_5_X = 6
export const YC_SPACING_2_X = 8
export const YC_SPACING_2_5_X = 10
export const YC_SPACING_3_X = 12
export const YC_SPACING_4_X = 16
export const YC_SPACING_5_X = 20
export const YC_SPACING_6_X = 24
export const YC_SPACING_7_X = 28
export const YC_SPACING_8_X = 32
export const YC_SPACING_9_X = 36
export const YC_SPACING_10_X = 40
export const YC_SPACING_11_X = 44
export const YC_SPACING_12_X = 48
export const YC_RADIUS_X = 4
export const YC_RADIUS_1_5_X = 6
export const YC_RADIUS_2_X = 8
export const YC_RADIUS_2_5_X = 10
export const YC_RADIUS_3_X = 12
export const YC_RADIUS_4_X = 16
export const YC_RADIUS_5_X = 20

export const YC_HEADER_H_1_SEMIBOLD_FAMILY = 'Inter'
export const YC_HEADER_H_1_SEMIBOLD_STYLE = 'Semi Bold'
export const YC_HEADER_H_1_SEMIBOLD_FONT_SIZE = 24
export const YC_HEADER_H_1_SEMIBOLD_LINE_HEIGHT = 32
export const YC_HEADER_H_1_SEMIBOLD_FONT_WEIGHT = '600'
export const YC_HEADER_H_2_SEMIBOLD_FAMILY = 'Inter'
export const YC_HEADER_H_2_SEMIBOLD_STYLE = 'Semi Bold'
export const YC_HEADER_H_2_SEMIBOLD_FONT_SIZE = 20
export const YC_HEADER_H_2_SEMIBOLD_LINE_HEIGHT = 26
export const YC_HEADER_H_2_SEMIBOLD_FONT_WEIGHT = '600'
export const YC_HEADER_H_3_SEMIBOLD_FAMILY = 'Inter'
export const YC_HEADER_H_3_SEMIBOLD_STYLE = 'Semi Bold'
export const YC_HEADER_H_3_SEMIBOLD_FONT_SIZE = 18
export const YC_HEADER_H_3_SEMIBOLD_LINE_HEIGHT = 24
export const YC_HEADER_H_3_SEMIBOLD_FONT_WEIGHT = '600'
export const YC_HEADER_H_4_SEMIBOLD_FAMILY = 'Inter'
export const YC_HEADER_H_4_SEMIBOLD_STYLE = 'Semi Bold'
export const YC_HEADER_H_4_SEMIBOLD_FONT_SIZE = 16
export const YC_HEADER_H_4_SEMIBOLD_LINE_HEIGHT = 22
export const YC_HEADER_H_4_SEMIBOLD_FONT_WEIGHT = '600'
export const YC_PARAGRAPH_P_1_REGULAR_FAMILY = 'Inter'
export const YC_PARAGRAPH_P_1_REGULAR_STYLE = 'Regular'
export const YC_PARAGRAPH_P_1_REGULAR_FONT_SIZE = 16
export const YC_PARAGRAPH_P_1_REGULAR_LINE_HEIGHT = 24
export const YC_PARAGRAPH_P_1_REGULAR_FONT_WEIGHT = '400'
export const YC_PARAGRAPH_P_1_MEDIUM_FAMILY = 'Inter'
export const YC_PARAGRAPH_P_1_MEDIUM_STYLE = 'Medium'
export const YC_PARAGRAPH_P_1_MEDIUM_FONT_SIZE = 16
export const YC_PARAGRAPH_P_1_MEDIUM_LINE_HEIGHT = 24
export const YC_PARAGRAPH_P_1_MEDIUM_FONT_WEIGHT = '500'
export const YC_PARAGRAPH_P_2_REGULAR_FAMILY = 'Inter'
export const YC_PARAGRAPH_P_2_REGULAR_STYLE = 'Regular'
export const YC_PARAGRAPH_P_2_REGULAR_FONT_SIZE = 14
export const YC_PARAGRAPH_P_2_REGULAR_LINE_HEIGHT = 20
export const YC_PARAGRAPH_P_2_REGULAR_FONT_WEIGHT = '400'
export const YC_PARAGRAPH_P_2_MEDIUM_FAMILY = 'Inter'
export const YC_PARAGRAPH_P_2_MEDIUM_STYLE = 'Medium'
export const YC_PARAGRAPH_P_2_MEDIUM_FONT_SIZE = 14
export const YC_PARAGRAPH_P_2_MEDIUM_LINE_HEIGHT = 20
export const YC_PARAGRAPH_P_2_MEDIUM_FONT_WEIGHT = '500'
export const YC_SUBHEAD_S_1_MEDIUM_FAMILY = 'Inter'
export const YC_SUBHEAD_S_1_MEDIUM_STYLE = 'Medium'
export const YC_SUBHEAD_S_1_MEDIUM_FONT_SIZE = 14
export const YC_SUBHEAD_S_1_MEDIUM_LINE_HEIGHT = 18
export const YC_SUBHEAD_S_1_MEDIUM_FONT_WEIGHT = '500'
export const YC_SUBHEAD_S_1_SEMIBOLD_FAMILY = 'Inter'
export const YC_SUBHEAD_S_1_SEMIBOLD_STYLE = 'Semi Bold'
export const YC_SUBHEAD_S_1_SEMIBOLD_FONT_SIZE = 14
export const YC_SUBHEAD_S_1_SEMIBOLD_LINE_HEIGHT = 18
export const YC_SUBHEAD_S_1_SEMIBOLD_FONT_WEIGHT = '600'
export const YC_ANNOTATION_A_1_REGULAR_FAMILY = 'Inter'
export const YC_ANNOTATION_A_1_REGULAR_STYLE = 'Regular'
export const YC_ANNOTATION_A_1_REGULAR_FONT_SIZE = 13
export const YC_ANNOTATION_A_1_REGULAR_LINE_HEIGHT = 18
export const YC_ANNOTATION_A_1_REGULAR_FONT_WEIGHT = '400'
export const YC_ANNOTATION_A_1_MEDIUM_FAMILY = 'Inter'
export const YC_ANNOTATION_A_1_MEDIUM_STYLE = 'Medium'
export const YC_ANNOTATION_A_1_MEDIUM_FONT_SIZE = 13
export const YC_ANNOTATION_A_1_MEDIUM_LINE_HEIGHT = 18
export const YC_ANNOTATION_A_1_MEDIUM_FONT_WEIGHT = '500'
export const YC_ANNOTATION_A_2_REGULAR_FAMILY = 'Inter'
export const YC_ANNOTATION_A_2_REGULAR_STYLE = 'Regular'
export const YC_ANNOTATION_A_2_REGULAR_FONT_SIZE = 12
export const YC_ANNOTATION_A_2_REGULAR_LINE_HEIGHT = 16
export const YC_ANNOTATION_A_2_REGULAR_FONT_WEIGHT = '400'
export const YC_ANNOTATION_A_2_MEDIUM_FAMILY = 'Inter'
export const YC_ANNOTATION_A_2_MEDIUM_STYLE = 'Medium'
export const YC_ANNOTATION_A_2_MEDIUM_FONT_SIZE = 12
export const YC_ANNOTATION_A_2_MEDIUM_LINE_HEIGHT = 16
export const YC_ANNOTATION_A_2_MEDIUM_FONT_WEIGHT = '500'
export const YC_ANNOTATION_A_3_MEDIUM_FAMILY = 'Inter'
export const YC_ANNOTATION_A_3_MEDIUM_STYLE = 'Medium'
export const YC_ANNOTATION_A_3_MEDIUM_FONT_SIZE = 11
export const YC_ANNOTATION_A_3_MEDIUM_LINE_HEIGHT = 14
export const YC_ANNOTATION_A_3_MEDIUM_FONT_WEIGHT = '500'
export const YC_ANNOTATION_A_4_MEDIUM_FAMILY = 'Inter'
export const YC_ANNOTATION_A_4_MEDIUM_STYLE = 'Medium'
export const YC_ANNOTATION_A_4_MEDIUM_FONT_SIZE = 9
export const YC_ANNOTATION_A_4_MEDIUM_LINE_HEIGHT = 12
export const YC_ANNOTATION_A_4_MEDIUM_FONT_WEIGHT = '500'

export const YC_CARD_DROP_SHADOW = '0px 2px 24px 0px rgba(0, 0, 0, 0.08)'
export const YC_POP_UP_DROP_SHADOW = '0px 12px 40px 0px rgba(0, 0, 0, 0.12)'
export const YC_MODAL_DROP_SHADOW = '0px 12px 48px 0px rgba(0, 0, 0, 0.24)'

export const YC_AVATAR_ICON_SIZE_100 = 16
export const YC_AVATAR_ICON_SIZE_300 = 24
export const YC_AVATAR_ICON_SIZE_500 = 24
export const YC_AVATAR_ICON_SIZE_800 = 72
export const YC_AVATAR_SIZE_100 = 24
export const YC_AVATAR_SIZE_300 = 32
export const YC_AVATAR_SIZE_500 = 40
export const YC_AVATAR_SIZE_800 = 120
export const YC_AVATAR_INITIAL_LINE_HEIGHT_SIZE_100 = 14
export const YC_AVATAR_INITIAL_LINE_HEIGHT_SIZE_300 = 16
export const YC_AVATAR_INITIAL_LINE_HEIGHT_SIZE_500 = 24
export const YC_AVATAR_INITIAL_LINE_HEIGHT_SIZE_800 = 36
export const YC_AVATAR_INITIAL_FONT_SIZE_SIZE_100 = 8
export const YC_AVATAR_INITIAL_FONT_SIZE_SIZE_300 = 10
export const YC_AVATAR_INITIAL_FONT_SIZE_SIZE_500 = 14
export const YC_AVATAR_INITIAL_FONT_SIZE_SIZE_800 = 36
